import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Login from "./components/atoms/LoginButton";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Web3Auth Prototype</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Web3Auth</a>
        </h1>

        <p className={styles.description}> Try to login below 👏</p>
        <Login />
      </main>
    </div>
  );
}
